#!/bin/bash

set -euo pipefail

if command -v zsh >/dev/null; then
    sudo chsh -s "$(command -v zsh)" "$USER"
fi


if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLs get.chezmoi.io)" -- init --apply https://github.com/dankaiser1808/dotfiles.git
fi

if [ ! -d "$HOME/.zsh" ]; then
    mkdir -p "$HOME/.zsh"
fi

# ohmyzsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# zsh auto-suggestions
git clone https://github.com/zsh-users/zsh-autosuggestions /usr/share/zsh/plugins/zsh-autosuggestions

# zsh syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /usr/share/zsh/plugins/zsh-syntax-highlighting
